#! /bin/bash
## set up proper testing environment;
## putting the appropriate library path into ~/.R/check.Renviron
## (should I try to preserve an existing check.Renviron file???)
echo "R_LIBS_SITE=`pwd`/library" > ~/.R/check.Renviron
echo "R_LIBS_USER=`pwd`/library" >> ~/.R/check.Renviron
## also need to set these for the batch file run
## (so that package dependencies are checked appropriately)
## export R_LIBS=""
## export R_LIBS_SITE=`pwd`/library
## export R_LIBS_USER=`pwd`/library
## run tests
R CMD BATCH --vanilla lme4deptests.R
## tear down testing environment
rm ~/.R/check.Renviron
## cleanup
## rm -Rf check (?)